import { useMemo, useState } from "react";
import { Activity, BarChart3, BrainCircuit, CloudRain, Cpu, Crosshair, Database, Gauge, Layers, MessageSquare, Radio, Send, ShieldCheck, SlidersHorizontal, Target, Thermometer, TrendingDown, Workflow, Wrench, Zap } from "lucide-react";
import { apiPost } from "../api/client";
import { useApi } from "../hooks/useApi";
import { BlastingResponse, DataQualityResponse, EquipmentResponse, ModelRegistryResponse, OverviewResponse, ProductionForecastResponse, ProductionHistoryRecord, ProspectivityCell, RecommendationResponse, WeatherResponse } from "../types/api";
import { ReserveMap } from "../components/ReserveMap";
import { number } from "../utils/format";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type SatelliteResponse = { scenes: Array<{id?:string;source?:string;date?:string;cloud_cover?:number;quality?:number;thermal_coverage?:number;bands?:string[]}>; count:number; data_mode:string };
const pct = (v:number) => `${Math.round(Math.max(0,Math.min(1,v))*100)}%`;
const tonnes = (v:number|null|undefined) => v == null ? "—" : v.toLocaleString("en-IN", {maximumFractionDigits:0});

type Scenario = "stabilize-production" | "redeploy-fleet" | "weather-buffer";

export function OverviewPage({ overview, production, recommendations, equipment, quality, reserveCells }: { overview: OverviewResponse; production: ProductionForecastResponse; recommendations: RecommendationResponse; equipment: EquipmentResponse; quality: DataQualityResponse; reserveCells: ProspectivityCell[] }) {
  const [selectedCell,setSelectedCell]=useState<ProspectivityCell|null>(null);
  const [question,setQuestion]=useState("");
  const [answer,setAnswer]=useState<{answer:string;confidence?:number;evidence?:string[]}|null>(null);
  const [asking,setAsking]=useState(false);
  const [scenario,setScenario]=useState<Scenario>("stabilize-production");
  const [simulation,setSimulation]=useState<RecommendationResponse|null>(null);
  const [simulating,setSimulating]=useState(false);
  const weather=useApi<WeatherResponse>("/api/v1/weather");
  const blasting=useApi<BlastingResponse>("/api/v1/blasting");
  const models=useApi<ModelRegistryResponse>("/api/v1/models");
  const history=useApi<{records:ProductionHistoryRecord[]}>("/api/v1/production/history?days=30");
  const satellite=useApi<SatelliteResponse>("/api/v1/satellite/scenes?limit=24");
  const risk=overview.shortfall_probability ?? production.shortfall_probability ?? 0;
  const gap=production.gap_mt;
  const fleet=equipment.fleet_utilization;
  const health=quality.overall_score;
  const topRec=recommendations.recommendations?.[0];
  const critical=useMemo(()=>equipment.items.slice().filter(x=>x.status!=="NORMAL").sort((a,b)=>b.downtime_7d_hours-a.downtime_7d_hours).slice(0,5),[equipment.items]);
  const evidenceScore=useMemo(()=>Math.max(0,Math.min(1,(health+Math.max(0,1-risk)+fleet)/3)),[health,risk,fleet]);
  const ask=async()=>{const q=question.trim();if(!q||asking)return;setAsking(true);try{const r=await apiPost<Record<string,unknown>>("/api/v1/chat",{message:q,context:{site_id:overview.site_id,data_mode:overview.data_mode,production_risk:risk,production_gap_mt:gap,fleet_utilization:fleet,data_quality:health,selected_target:selectedCell?.id??null}});setAnswer({answer:String(r.answer??"No response returned."),confidence:typeof r.confidence==="number"?r.confidence:undefined,evidence:Array.isArray(r.evidence)?r.evidence.map(String):undefined});}catch(e){setAnswer({answer:`Copilot unavailable: ${String(e)}`});}finally{setAsking(false);}};
  const simulate=async()=>{if(simulating)return;setSimulating(true);try{const r=await apiPost<RecommendationResponse>("/api/v1/recommendations/simulate",{scenario,production_gap_mt:Math.abs(gap),equipment_redeployment:scenario==="redeploy-fleet",weather_buffer:scenario==="weather-buffer"});setSimulation(r);}catch(e){setSimulation(null);}finally{setSimulating(false);}};
  return <section className="cc-page">
    <header className="cc-hero"><div><span className="cc-kicker"><Crosshair size={14}/> MINE INTELLIGENCE COMMAND CENTER</span><h1>{overview.site_name||"MANGAI Demo Mine"}</h1><p>One operational picture across geology, reserve potential, production, fleet, weather, blasting and model health.</p></div><div className="cc-state"><span className="cc-pulse"/> SYSTEM READY <small>{overview.data_mode||"DEMO"}</small></div></header>
    <div className="cc-grid">
      <article className="cc-map-card cc-panel cc-span-8"><div className="cc-panel-head"><div><span className="cc-label">GEOSPATIAL INTELLIGENCE</span><strong>Prospectivity field</strong></div><span className="cc-map-mode"><Layers size={14}/> {reserveCells.length} TARGETS</span></div><div className="cc-real-map"><ReserveMap cells={reserveCells} selectedCell={selectedCell} onSelect={setSelectedCell} layer="probability" boreholes={[]}/></div><div className="cc-map-footer"><span><Layers size={13}/> PROBABILITY · GRADE · THICKNESS · CONFIDENCE</span><em>PROTOTYPE RESOURCE POTENTIAL · HUMAN VALIDATION REQUIRED</em></div></article>
      <aside className="cc-panel cc-span-4 cc-rail"><div className="cc-panel-head"><div><span className="cc-label">LIVE SIGNALS</span><strong>Intelligence rail</strong></div><Activity size={16}/></div><Signal label="PRODUCTION RISK" value={pct(risk)} detail={production.severity+" · primary driver: "+(production.top_drivers?.[0]?.feature??"monitoring")} ratio={risk} risk/><Signal label="FLEET UTILIZATION" value={pct(fleet)} detail={`${equipment.critical_equipment_count} critical assets · ${equipment.items.length} tracked`} ratio={fleet}/><Signal label="DATA HEALTH" value={pct(health)} detail={`${quality.runs.length} datasets observed`} ratio={health}/><div className="cc-action"><span>AI PRIORITY</span><strong>{topRec?.title??"No priority action"}</strong><small>{topRec?.rationale??"Monitor current operating signals."}</small></div></aside>
      <MetricFeature icon={TrendingDown} label="7-DAY PRODUCTION" value={`${tonnes(production.forecast_mt)} t`} detail={`Target ${tonnes(production.target_mt)} t · ${production.model_version}`}/><MetricFeature icon={Target} label="SHORTFALL GAP" value={`${gap<0?"":"+"}${tonnes(gap)} t`} detail={`Risk ${pct(risk)} · ${production.severity}`} risk={gap<0}/><MetricFeature icon={Wrench} label="FLEET AVAILABILITY" value={pct(equipment.fleet_availability)} detail={`${equipment.critical_equipment_count} critical · ${number(equipment.items.length)} assets`} risk={equipment.critical_equipment_count>0}/>
      <article className="cc-panel cc-span-12 cc-decision-cockpit"><div className="cc-panel-head"><div><span className="cc-label"><BrainCircuit size={13}/> DECISION COCKPIT</span><strong>Scenario intelligence</strong></div><span className="cc-map-mode">SIMULATION · NO PLAN CHANGE</span></div><div className="cc-cockpit-grid"><div className="cc-scenario-controls"><label>Scenario</label><button className={scenario==="stabilize-production"?"active":""} onClick={()=>setScenario("stabilize-production")}><Zap size={14}/><span>Stabilize production</span><small>Reduce current shortfall exposure</small></button><button className={scenario==="redeploy-fleet"?"active":""} onClick={()=>setScenario("redeploy-fleet")}><Wrench size={14}/><span>Redeploy fleet</span><small>Stress-test equipment availability</small></button><button className={scenario==="weather-buffer"?"active":""} onClick={()=>setScenario("weather-buffer")}><CloudRain size={14}/><span>Weather buffer</span><small>Protect against environmental delay</small></button><button className="cc-simulate" onClick={()=>void simulate()} disabled={simulating}><SlidersHorizontal size={14}/>{simulating?"Running simulation…":"Run what-if simulation"}</button></div><div className="cc-cockpit-state"><div className="cc-cockpit-score"><span>DECISION EVIDENCE SCORE</span><strong>{pct(evidenceScore)}</strong><small>Derived from current data quality, fleet utilization and inverse production risk.</small></div><div className="cc-cockpit-thread"><Thread label="ENVIRONMENT" value={weather.data?.weather_risk??"WAIT"}/><Thread label="BLASTING" value={blasting.data?.overlap_risk??"WAIT"}/><Thread label="EQUIPMENT" value={`${equipment.critical_equipment_count} critical`}/><Thread label="PRODUCTION" value={production.severity}/></div>{simulation&&<div className="cc-simulation-result"><b>SIMULATION RESULT</b><span>{simulation.recommendations?.[0]?.title??"Scenario evaluated"}</span><small>{simulation.recommendations?.[0]?.rationale??"Review returned recommendation evidence."}</small></div>}</div></div></article>
      <article className="cc-panel cc-span-7 cc-relationship"><div className="cc-panel-head"><div><span className="cc-label">TARGET INTELLIGENCE</span><strong>{selectedCell?.id??"Select a prospectivity target"}</strong></div><Target size={16}/></div>{selectedCell?<><div className="cc-target-grid"><Value label="PROSPECTIVITY" value={pct(selectedCell.probability)}/><Value label="MN GRADE" value={`${number(selectedCell.predicted_grade_pct,1)}%`}/><Value label="THICKNESS" value={`${number(selectedCell.predicted_thickness_m,1)} m`}/><Value label="CONFIDENCE" value={pct(selectedCell.confidence)}/></div><div className="cc-evidence-line">Top evidence: {selectedCell.top_contributors.slice(0,3).map(x=>`${x.feature} (${x.direction})`).join(" · ")}</div></>:<p>Select a target to expose predicted grade, thickness, confidence and model contributors.</p>}<p className="cc-note">Prototype resource potential is not an official reserve estimate.</p></article>
      <article className="cc-panel cc-span-5 cc-integrity"><div className="cc-panel-head"><div><span className="cc-label">SYSTEM INTEGRITY</span><strong>Model + data state</strong></div><ShieldCheck size={16}/></div><Integrity icon={Cpu} label="AI services" value={overview.model_health}/><Integrity icon={Database} label="Data pipeline" value={pct(health)}/><Integrity icon={Radio} label="Satellite records" value={String(satellite.data?.count??0)}/><Integrity icon={ShieldCheck} label="Decision boundary" value="ACTIVE"/></article>
      <article className="cc-panel cc-span-7"><div className="cc-panel-head"><div><span className="cc-label"><BarChart3 size={13}/> PRODUCTION INTELLIGENCE</span><strong>Actual vs target vs forecast</strong></div><span className="cc-map-mode">30-DAY HISTORY</span></div><div className="cc-chart"><ResponsiveContainer width="100%" height={270}><LineChart data={history.data?.records??[]}><CartesianGrid stroke="#dfe9e4" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={28} stroke="#647b72" fontSize={10}/><YAxis stroke="#647b72" fontSize={10}/><Tooltip contentStyle={{background:"#ffffff",border:"1px solid #cfe1d9",color:"#173128"}}/><Line type="monotone" dataKey="production_mt" stroke="#079a6b" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="target_mt" stroke="#c58a1b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></article>
      <article className="cc-panel cc-span-5"><div className="cc-panel-head"><div><span className="cc-label"><Activity size={13}/> PRODUCTION DRIVERS</span><strong>Why risk moves</strong></div><span className="cc-map-mode">MODEL EVIDENCE</span></div><div className="cc-driver-list">{production.top_drivers.slice(0,5).map(d=><div className="cc-driver" key={d.feature}><div><span>{d.feature}</span><b>{d.direction}</b></div><i><em style={{width:`${Math.max(8,Math.min(100,d.importance*100))}%`}}/></i></div>)}</div></article>
      <article className="cc-panel cc-span-4"><div className="cc-panel-head"><div><span className="cc-label"><CloudRain size={13}/> WEATHER</span><strong>{weather.data?.weather_risk??"LOADING"}</strong></div></div>{weather.data&&<><Metric label="Rainfall 7d" value={`${number(weather.data.rainfall_7d_mm,1)} mm`}/><Metric label="Soil moisture" value={pct(weather.data.soil_moisture)}/><Metric label="Temperature" value={`${number(weather.data.temperature_c,1)} °C`}/></>}</article>
      <article className="cc-panel cc-span-4"><div className="cc-panel-head"><div><span className="cc-label"><Activity size={13}/> BLASTING</span><strong>{blasting.data?.overlap_risk??"LOADING"}</strong></div></div>{blasting.data&&<><Metric label="Planned blasts" value={String(blasting.data.planned_blasts_7d)}/><Metric label="Delay 7d" value={`${number(blasting.data.delay_hours_7d,1)} h`}/><Metric label="Trend" value={blasting.data.delay_trend}/></>}</article>
      <article className="cc-panel cc-span-4"><div className="cc-panel-head"><div><span className="cc-label"><Wrench size={13}/> CRITICAL FLEET</span><strong>{equipment.critical_equipment_count} critical</strong></div></div><div className="cc-mini-list">{critical.map(x=><div key={x.equipment_id}><span>{x.equipment_id}</span><b>{x.status}</b><small>{number(x.downtime_7d_hours,1)}h downtime</small></div>)}{!critical.length&&<p className="muted">No non-normal assets.</p>}</div></article>
      <article className="cc-panel cc-span-7"><div className="cc-panel-head"><div><span className="cc-label"><Target size={13}/> RECOMMENDATION ENGINE</span><strong>Priority actions</strong></div><span className="cc-map-mode">{recommendations.recommendations.length} PROPOSED</span></div><div className="cc-recs">{recommendations.recommendations.slice(0,4).map(r=><div className="cc-rec" key={r.id}><div><span className={`priority ${r.priority.toLowerCase()}`}>{r.priority}</span><b>{r.title}</b></div><p>{r.rationale}</p><small>Confidence {pct(r.confidence)} · impact {JSON.stringify(r.estimated_impact)}</small></div>)}</div></article>
      <article className="cc-panel cc-span-5"><div className="cc-panel-head"><div><span className="cc-label"><Database size={13}/> MODEL HEALTH</span><strong>Registry + quality</strong></div></div><Metric label="Models registered" value={String(models.data?.models.length??0)}/><Metric label="Overall data quality" value={pct(health)}/><Metric label="Datasets" value={String(quality.runs.length)}/><Metric label="Lowest dataset score" value={quality.runs.length?`${Math.round(Math.min(...quality.runs.map(x=>x.quality_score))*100)}%`:"—"}/></article>
      <article className="cc-panel cc-span-12 cc-digital-thread"><div className="cc-panel-head"><div><span className="cc-label"><Workflow size={13}/> DIGITAL TWIN THREAD</span><strong>Environment → geology → operations → outcome</strong></div><span className="cc-map-mode">CROSS-DOMAIN TRACE</span></div><div className="cc-thread-flow"><Thread label="ENVIRONMENT" value={weather.data?.weather_risk??"loading"}/><span className="cc-thread-arrow">→</span><Thread label="GEOLOGY / RESERVE" value={selectedCell?.prospectivity_class??"target field"}/><span className="cc-thread-arrow">→</span><Thread label="MINE OPERATIONS" value={`${equipment.critical_equipment_count} critical`}/><span className="cc-thread-arrow">→</span><Thread label="PRODUCTION" value={`${pct(risk)} risk`}/><span className="cc-thread-arrow">→</span><Thread label="ACTION" value={topRec?.priority??"monitor"}/></div></article>
      <article className="cc-panel cc-span-12"><div className="cc-panel-head"><div><span className="cc-label"><Thermometer size={13}/> SATELLITE INTELLIGENCE</span><strong>Remote-sensing evidence</strong></div><span className="cc-map-mode">{satellite.data?.count??0} RECORDS · {satellite.data?.data_mode??"CONNECTING"}</span></div><div className="satellite-strip"><div className="satellite-summary"><MetricMini label="Records" value={String(satellite.data?.count??0)}/><MetricMini label="Best quality" value={satellite.data?.scenes.length?`${Math.round(Math.max(...satellite.data.scenes.map(x=>x.quality??0))*100)}%`:"—"}/><MetricMini label="Thermal" value={satellite.data?.scenes.filter(x=>x.thermal_coverage!=null).length?"Available":"Context only"}/></div><div className="satellite-events">{(satellite.data?.scenes??[]).slice(0,6).map((s,i)=><span key={s.id??i}><b>{s.source??"Feature field"}</b>{s.date??"observation"}</span>)}</div></div></article>
      <article className="cc-panel cc-span-12 cc-copilot"><div className="cc-panel-head"><div><span className="cc-label"><MessageSquare size={13}/> EVIDENCE COPILOT</span><strong>Investigate the current mine state</strong></div><span className="cc-map-mode">BOUNDED DECISION SUPPORT</span></div><div className="cc-copilot-body"><div className="cc-copilot-prompts"><button onClick={()=>setQuestion("Why is production at risk right now?")}>Why production risk?</button><button onClick={()=>setQuestion("What should the operator investigate next?")}>What next?</button><button onClick={()=>setQuestion("Which signals support the highest-priority recommendation?")}>Show evidence</button><button onClick={()=>setQuestion("Explain the selected reserve target and its confidence.")}>Explain target</button></div><div className="cc-copilot-row"><div className="cc-copilot-input-wrap"><BrainCircuit size={15}/><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder="Ask about production, reserve targets, fleet, weather, blasting or recommendations…"/><span>ENTER</span></div><button className="cc-copilot-send" onClick={()=>void ask()} disabled={asking||!question.trim()}><Send size={14}/>{asking?"Analyzing":"Ask MANGAI"}</button></div>{answer&&<div className="cc-copilot-answer"><div><span>MODEL RESPONSE</span>{answer.confidence!=null&&<b>{pct(answer.confidence)} confidence</b>}</div><p>{answer.answer}</p>{answer.evidence?.length?<div className="cc-answer-evidence">{answer.evidence.map((item,i)=><span key={i}>{item}</span>)}</div>:null}<small>Decision support only. Verify with accountable mine personnel and site procedures.</small></div>}</div></article>
    </div>
  </section>;
}
function Signal({label,value,detail,ratio,risk}:{label:string;value:string;detail:string;ratio:number;risk?:boolean}){return <div className={`cc-signal ${risk?"cc-risk":""}`}><div><span>{label}</span><strong>{value}</strong></div><small>{detail}</small><div className="cc-bar"><i style={{width:`${Math.max(2,Math.min(100,ratio*100))}%`}}/></div></div>}
function MetricFeature({icon:Icon,label,value,detail,risk}:{icon:typeof Activity;label:string;value:string;detail:string;risk?:boolean}){return <article className="cc-panel cc-span-4 cc-metric-feature"><span className="cc-label"><Icon size={14}/> {label}</span><strong className={risk?"risk-text":""}>{value}</strong><small>{detail}</small></article>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-line"><span>{label}</span><strong>{value}</strong></div>}
function Value({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Integrity({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:string}){return <div className="cc-integrity-row"><span><Icon size={14}/>{label}</span><b>{value}</b></div>}
function MetricMini({label,value}:{label:string;value:string}){return <div className="sat-mini"><span>{label}</span><strong>{value}</strong></div>}
function Thread({label,value}:{label:string;value:string}){return <div className="cc-thread-node"><span>{label}</span><strong>{value}</strong></div>}
