import { Satellite, Thermometer, Cloud, Activity, Radio } from "lucide-react";

type Scene = { id?: string; source?: string; date?: string; cloud_cover?: number; quality?: number; bands?: string[]; thermal_coverage?: number };
const Header = ({ icon: Icon, title, meta }: { icon: typeof Satellite; title: string; meta: string }) => <div className="panel-header"><div className="panel-title"><Icon size={16}/><span>{title}</span></div><span className="panel-meta">{meta}</span></div>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="metric-line"><span>{label}</span><strong>{value}</strong></div>;
export function SatellitePage({ scenes = [] }: { scenes?: Scene[] }) {
  const thermal = scenes.filter(s => (s.source ?? "").toLowerCase().includes("landsat") || s.thermal_coverage !== undefined);
  const sentinel = scenes.filter(s => (s.source ?? "").toLowerCase().includes("sentinel"));
  return <div className="page-grid satellite-layout">
    <section className="panel wide satellite-stage"><Header icon={Satellite} title="Satellite Intelligence" meta={`${scenes.length} scenes · temporal evidence`} /><div className="satellite-visual" role="img" aria-label="Satellite intelligence evidence field"><div className="sat-grid"/><div className="sat-orbit orbit-a"/><div className="sat-orbit orbit-b"/><div className="sat-scan"><span>REMOTE-SENSING EVIDENCE FIELD</span><span>MULTISPECTRAL / THERMAL</span></div><div className="thermal-hotspot hotspot-a"/><div className="thermal-hotspot hotspot-b"/><div className="sat-coordinates">AOI 21.60°N · 80.19°E<br/>DEMO PROXY · NOT OFFICIAL SURVEY</div></div></section>
    <section className="panel"><Header icon={Thermometer} title="Thermal Field" meta="Landsat"/><Metric label="Thermal scenes" value={String(thermal.length)}/><Metric label="Coverage" value={thermal.length ? `${Math.round((thermal[0].thermal_coverage ?? 1) * 100)}%` : "—"}/><Metric label="Signal" value="Surface-temperature proxy"/><p className="muted">Thermal imagery is contextual evidence. Validate anomalous signatures against geology and field observations.</p></section>
    <section className="panel"><Header icon={Radio} title="Scene Quality" meta="ingestion"/><Metric label="Sentinel-2" value={String(sentinel.length)}/><Metric label="Landsat" value={String(thermal.length)}/><Metric label="Best quality" value={scenes.length ? `${Math.round(Math.max(...scenes.map(s => s.quality ?? 0)) * 100)}%` : "—"}/><Metric label="Cloud-free" value={scenes.length ? `${Math.round(Math.max(...scenes.map(s => 1 - (s.cloud_cover ?? 0))) * 100)}%` : "—"}/></section>
    <section className="panel wide"><Header icon={Cloud} title="Evidence Timeline" meta="multisource"/><div className="scene-timeline">{scenes.slice(0, 12).map((scene, i) => <article className="scene-row" key={scene.id ?? i}><div><strong>{scene.source ?? "Satellite"}</strong><span>{scene.date ?? "Unknown acquisition"}</span></div><span>{scene.cloud_cover !== undefined ? `${Math.round(scene.cloud_cover * 100)}% cloud` : "cloud n/a"}</span><span>{scene.bands?.join(", ") ?? "multispectral"}</span></article>)}</div>{!scenes.length && <p className="muted">No live scene metadata is currently exposed by the API. The intelligence surface is ready for Sentinel-2/Landsat ingestion.</p>}</section>
    <section className="panel wide"><Header icon={Activity} title="Scientific Boundary" meta="required"/><p className="muted">Satellite signals support prospectivity screening and operational context; they do not independently establish mineral reserves. DEMO PROXY labels remain active until validated field data are connected.</p></section>
  </div>;
}
