import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CloudRain, Database, Gauge, Layers3, Map, Menu, Radio, Settings, ShieldCheck, Target, Wrench, X } from "lucide-react";
import { apiPost } from "./api/client";
import { useApi } from "./hooks/useApi";
import { BlastingResponse, DataQualityResponse, EquipmentResponse, ModelRegistryResponse, OverviewResponse, ProductionForecastResponse, ProductionHistoryRecord, ProspectivityCell, RecommendationResponse, ReserveProspectivityResponse, ReserveSummaryResponse, WeatherResponse } from "./types/api";
import { ReserveMap } from "./components/ReserveMap";
import { OverviewPage } from "./pages/OverviewPage";
import { SatellitePage } from "./pages/SatellitePage";
import { OperationsPage } from "./pages/OperationsPage";
import { compactNumber, number, percent, signedNumber } from "./utils/format";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type PageKey = "overview" | "reserve" | "production" | "operations" | "satellite" | "equipment" | "weather" | "recommendations" | "health" | "settings";
const pages: Array<{ key: PageKey; label: string; icon: typeof Activity }> = [
  { key: "overview", label: "Overview", icon: Gauge }, { key: "reserve", label: "Reserve Intelligence", icon: Map }, { key: "production", label: "Production Intelligence", icon: BarChart3 }, { key: "operations", label: "Operations", icon: Activity }, { key: "equipment", label: "Equipment", icon: Wrench }, { key: "weather", label: "Weather + Blasting", icon: CloudRain }, { key: "satellite", label: "Satellite Intelligence", icon: Radio }, { key: "recommendations", label: "Recommendation Center", icon: Target }, { key: "health", label: "Model + Data Health", icon: Database }, { key: "settings", label: "Settings", icon: Settings }
];

type Scene = { id?: string; source?: string; date?: string; cloud_cover?: number; quality?: number; bands?: string[]; thermal_coverage?: number };

export default function App() {
  const [activePage, setActivePage] = useState<PageKey>("overview");
  const [threshold, setThreshold] = useState(0.55);
  const [layer, setLayer] = useState<"probability" | "grade" | "thickness" | "confidence">("probability");
  const [selectedCell, setSelectedCell] = useState<ProspectivityCell | null>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [now, setNow] = useState(new Date());

  const overview = useApi<OverviewResponse>("/api/v1/overview");
  const reserveSummary = useApi<ReserveSummaryResponse>("/api/v1/reserves/summary");
  const reserveCells = useApi<ReserveProspectivityResponse>(`/api/v1/reserves/prospectivity?limit=450&min_probability=${threshold.toFixed(2)}`);
  const boreholes = useApi<{ boreholes: Array<{ borehole_id: string; latitude: number; longitude: number; lithology?: string }> }>("/api/v1/reserves/boreholes?limit=250");
  const production = useApi<ProductionForecastResponse>("/api/v1/production/forecast?horizon=7");
  const productionHistory = useApi<{ records: ProductionHistoryRecord[] }>("/api/v1/production/history?days=90");
  const equipment = useApi<EquipmentResponse>("/api/v1/equipment");
  const weather = useApi<WeatherResponse>("/api/v1/weather");
  const blasting = useApi<BlastingResponse>("/api/v1/blasting");
  const recommendations = useApi<RecommendationResponse>("/api/v1/recommendations");
  const models = useApi<ModelRegistryResponse>("/api/v1/models");
  const dataQuality = useApi<DataQualityResponse>("/api/v1/data-quality");
  const safety = useApi<{ mode: string; boundary: string }>("/api/v1/settings/safety");
  const satellite = useApi<{ scenes: Scene[]; count: number; data_mode: string }>("/api/v1/satellite/scenes?limit=24");

  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { setMobileNav(false); }, [activePage]);

  const loading = overview.loading || production.loading;
  const error = overview.error || production.error;
  const ready = Boolean(overview.data && production.data);
  const status = overview.data?.model_health ?? "INITIALIZING";
  const sceneCount = satellite.data?.count ?? 0;
  const page = useMemo(() => pages.find(item => item.key === activePage)!, [activePage]);

  return <div className="app">
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}>
      <div className="brand"><div className="brand-mark">M</div><div><h1>MANGAI</h1><span>Industrial Geospatial Intelligence</span></div><button className="mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={18}/></button></div>
      <nav aria-label="Intelligence navigation">{pages.map(item => { const Icon = item.icon; return <button key={item.key} aria-current={activePage === item.key ? "page" : undefined} className={activePage === item.key ? "nav-item active" : "nav-item"} onClick={() => setActivePage(item.key)}><Icon size={17}/><span>{item.label}</span></button>; })}</nav>
      <div className="sidebar-foot"><ShieldCheck size={17}/><span>{status}</span><small>decision support</small></div>
    </aside>
    {mobileNav && <button className="nav-backdrop" onClick={() => setMobileNav(false)} aria-label="Close navigation"/>}
    <main className="main">
      <header className="topbar">
        <button className="mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20}/></button>
        <div className="topbar-title"><p className="eyebrow">SIH 26009 · MOIL · MINISTRY OF STEEL</p><h2>{page.label}</h2><span>{overview.data?.site_name ?? "MANGAI Demo Mine"} · {now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span></div>
        <div className="command-status"><span className="status-dot"/><span>SYSTEM {status}</span><span className="badge warn">DEMO / SYNTHETIC</span><span className="badge">{sceneCount} satellite scenes</span></div>
      </header>
      <div className="global-boundary"><span>DECISION SUPPORT ONLY</span><span>Prototype outputs are not official reserves or safety clearance.</span></div>
      {loading && <StatePanel label="Loading MANGAI intelligence services…"/>}
      {error && <StatePanel label={`API unavailable: ${error}`} tone="danger"/>}
      {ready && overview.data && production.data && <>
        {activePage === "overview" && recommendations.data && equipment.data && dataQuality.data && reserveCells.data && <OverviewPage overview={overview.data} production={production.data} recommendations={recommendations.data} equipment={equipment.data} quality={dataQuality.data} reserveCells={reserveCells.data.cells}/>} 
        {activePage === "reserve" && reserveSummary.data && reserveCells.data && <ReservePage summary={reserveSummary.data} cells={reserveCells.data.cells} boreholes={boreholes.data?.boreholes ?? []} threshold={threshold} setThreshold={setThreshold} layer={layer} setLayer={setLayer} selectedCell={selectedCell} setSelectedCell={setSelectedCell}/>} 
        {activePage === "production" && <ProductionPage forecast={production.data} history={productionHistory.data?.records ?? []}/>} 
        {activePage === "operations" && equipment.data && weather.data && blasting.data && <OperationsPage equipment={equipment.data} weather={weather.data} blasting={blasting.data} production={production.data}/>} 
        {activePage === "equipment" && equipment.data && <EquipmentPage equipment={equipment.data}/>} 
        {activePage === "weather" && weather.data && blasting.data && <WeatherBlastingPage weather={weather.data} blasting={blasting.data}/>} 
        {activePage === "satellite" && <SatellitePage scenes={satellite.data?.scenes ?? []}/>} 
        {activePage === "recommendations" && recommendations.data && <RecommendationsPage initial={recommendations.data}/>} 
        {activePage === "health" && models.data && dataQuality.data && <HealthPage models={models.data} dataQuality={dataQuality.data} boundary={overview.data.boundary_notice}/>} 
        {activePage === "settings" && <SettingsPage safety={safety.data}/>} 
      </>}
    </main>
  </div>;
}

function StatePanel({ label, tone = "default" }: { label: string; tone?: "default" | "danger" }) { return <section className={tone === "danger" ? "state danger" : "state"} role={tone === "danger" ? "alert" : "status"}>{label}</section>; }
function PanelHeader({ icon: Icon, title, meta }: { icon: typeof Activity; title: string; meta: string }) { return <div className="panel-header"><div className="panel-title"><Icon size={16}/><span>{title}</span></div><span className="panel-meta">{meta}</span></div>; }
function MetricLine({ label, value }: { label: string; value: string }) { return <div className="metric-line"><span>{label}</span><strong>{value}</strong></div>; }
function MetricCard({ icon: Icon, label, value, tone = "ok" }: { icon: typeof Activity; label: string; value: string; tone?: "ok" | "risk" }) { return <div className={`metric-card ${tone}`}><Icon size={17}/><span>{label}</span><strong>{value}</strong></div>; }
function DriverList({ drivers }: { drivers: Array<{ feature: string; direction: string; importance: number; value?: number | string | null }> }) { return <div className="driver-list">{drivers.slice(0, 5).map(driver => <div className="driver" key={`${driver.feature}-${driver.direction}`}><span>{driver.feature}</span><i style={{ width: `${Math.min(100, Math.max(6, driver.importance * 100))}%` }}/><b>{driver.direction}</b></div>)}</div>; }

function ReservePage({ summary, cells, boreholes, threshold, setThreshold, layer, setLayer, selectedCell, setSelectedCell }: { summary: ReserveSummaryResponse; cells: ProspectivityCell[]; boreholes: Array<{ borehole_id: string; latitude: number; longitude: number; lithology?: string }>; threshold: number; setThreshold: (v: number) => void; layer: "probability" | "grade" | "thickness" | "confidence"; setLayer: (v: "probability" | "grade" | "thickness" | "confidence") => void; selectedCell: ProspectivityCell | null; setSelectedCell: (c: ProspectivityCell) => void }) {
  return <div className="page-grid reserve-layout"><section className="panel wide"><PanelHeader icon={Layers3} title="Reserve Intelligence" meta={`${cells.length} cells · spatial model`}/><div className="toolbar"><label>Prospectivity threshold <input aria-label="Prospectivity threshold" type="range" min="0" max="0.95" step="0.05" value={threshold} onChange={e => setThreshold(Number(e.target.value))}/><strong>{percent(threshold)}</strong></label><div className="layer-toggles">{(["probability", "grade", "thickness", "confidence"] as const).map(item => <button key={item} className={layer === item ? "chip active" : "chip"} aria-pressed={layer === item} onClick={() => setLayer(item)}>{item}</button>)}</div></div><ReserveMap cells={cells} selectedCell={selectedCell} onSelect={setSelectedCell} layer={layer} boreholes={boreholes}/></section><section className="panel detail-panel"><PanelHeader icon={Target} title="Target Intelligence" meta={selectedCell?.prospectivity_class ?? "select target"}/>{selectedCell ? <div className="detail-stack"><h3>{selectedCell.id}</h3><MetricLine label="Coordinates" value={`${number(selectedCell.latitude, 4)}, ${number(selectedCell.longitude, 4)}`}/><MetricLine label="Prospectivity" value={percent(selectedCell.probability)}/><MetricLine label="Predicted grade" value={`${number(selectedCell.predicted_grade_pct, 1)}% Mn`}/><MetricLine label="Predicted thickness" value={`${number(selectedCell.predicted_thickness_m, 1)} m`}/><MetricLine label="Confidence" value={percent(selectedCell.confidence)}/><MetricLine label="Resource P50" value={`${compactNumber(selectedCell.resource_potential.p50)} t`}/><DriverList drivers={selectedCell.top_contributors}/><p className="muted">Prototype resource potential only. Field verification is required before any reserve classification.</p></div> : <p className="muted">Select a target to inspect probability, grade, thickness, confidence and model evidence.</p>}</section><section className="panel"><PanelHeader icon={Gauge} title="Reserve Summary" meta="prototype"/><MetricLine label="High cells" value={number(summary.high_prospectivity_cells)}/><MetricLine label="Very high cells" value={number(summary.very_high_prospectivity_cells)}/><MetricLine label="Average grade" value={`${number(summary.average_predicted_grade_pct, 1)}% Mn`}/><MetricLine label="Average thickness" value={`${number(summary.average_predicted_thickness_m, 1)} m`}/><MetricLine label="Area" value={`${number(summary.high_prospectivity_area_ha, 1)} ha`}/></section></div>;
}

function ProductionPage({ forecast, history }: { forecast: ProductionForecastResponse; history: ProductionHistoryRecord[] }) { return <div className="page-grid"><section className="kpi-grid"><MetricCard icon={Activity} label="7-day forecast" value={`${compactNumber(forecast.forecast_mt)} t`}/><MetricCard icon={Target} label="Target" value={`${compactNumber(forecast.target_mt)} t`}/><MetricCard icon={BarChart3} label="Gap" value={`${signedNumber(forecast.gap_mt)} t`} tone={forecast.gap_mt < 0 ? "risk" : "ok"}/><MetricCard icon={Gauge} label="Shortfall risk" value={percent(forecast.shortfall_probability)} tone={forecast.shortfall_probability > .65 ? "risk" : "ok"}/></section><section className="panel wide chart-panel"><PanelHeader icon={BarChart3} title="Production Outlook" meta="actual · target · 90-day history"/><ResponsiveContainer width="100%" height={340}><LineChart data={history}><CartesianGrid stroke="rgba(145,174,162,.14)" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={28} stroke="#6f847b"/><YAxis width={68} stroke="#6f847b"/><Tooltip/><Line type="monotone" dataKey="production_mt" stroke="#35d39f" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="target_mt" stroke="#e7b75b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></section><section className="panel"><PanelHeader icon={Activity} title="Why the forecast moves" meta={forecast.severity}/><DriverList drivers={forecast.top_drivers}/></section><section className="panel"><PanelHeader icon={Gauge} title="Uncertainty" meta={forecast.forecast_date}/><MetricLine label="P10" value={`${compactNumber(forecast.prediction_interval.p10)} t`}/><MetricLine label="P50" value={`${compactNumber(forecast.prediction_interval.p50)} t`}/><MetricLine label="P90" value={`${compactNumber(forecast.prediction_interval.p90)} t`}/><MetricLine label="Baseline" value={`${compactNumber(forecast.baseline_forecast_mt)} t`}/></section></div>; }

function EquipmentPage({ equipment }: { equipment: EquipmentResponse }) { const ranked = equipment.items.slice().sort((a, b) => b.downtime_7d_hours - a.downtime_7d_hours).slice(0, 12); return <div className="page-grid"><section className="kpi-grid"><MetricCard icon={ShieldCheck} label="Fleet availability" value={percent(equipment.fleet_availability)}/><MetricCard icon={Gauge} label="Fleet utilization" value={percent(equipment.fleet_utilization)}/><MetricCard icon={Wrench} label="Critical equipment" value={number(equipment.critical_equipment_count)} tone={equipment.critical_equipment_count > 0 ? "risk" : "ok"}/></section><section className="panel wide chart-panel"><PanelHeader icon={Wrench} title="Fleet Downtime" meta={`${equipment.items.length} assets`}/><ResponsiveContainer width="100%" height={320}><BarChart data={ranked}><CartesianGrid stroke="rgba(145,174,162,.14)" strokeDasharray="3 3"/><XAxis dataKey="equipment_id" stroke="#6f847b"/><YAxis stroke="#6f847b"/><Tooltip/><Bar dataKey="downtime_7d_hours" fill="#e7b75b"/></BarChart></ResponsiveContainer></section><section className="panel wide table-panel"><PanelHeader icon={Layers3} title="Digital Fleet Grid" meta="telemetry snapshot"/><div className="data-table-wrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Avail.</th><th>Util.</th><th>Downtime</th><th>Status</th></tr></thead><tbody>{equipment.items.map(item => <tr key={item.equipment_id}><td className="mono">{item.equipment_id}</td><td>{item.equipment_type}</td><td>{percent(item.availability)}</td><td>{percent(item.utilization)}</td><td>{number(item.downtime_7d_hours, 1)} h</td><td><span className={`priority ${item.status.toLowerCase()}`}>{item.status}</span></td></tr>)}</tbody></table></div></section></div>; }

function WeatherBlastingPage({ weather, blasting }: { weather: WeatherResponse; blasting: BlastingResponse }) { return <div className="page-grid"><section className="kpi-grid"><MetricCard icon={CloudRain} label="Rainfall / 7d" value={`${number(weather.rainfall_7d_mm, 1)} mm`}/><MetricCard icon={Activity} label="Soil moisture" value={number(weather.soil_moisture, 2)}/><MetricCard icon={CloudRain} label="Weather risk" value={weather.weather_risk} tone={weather.weather_risk === "HIGH" ? "risk" : "ok"}/><MetricCard icon={Target} label="Blast overlap" value={blasting.overlap_risk} tone={blasting.overlap_risk === "HIGH" ? "risk" : "ok"}/></section><section className="panel wide"><PanelHeader icon={CloudRain} title="Weather + Blasting" meta={`${weather.latest_date} · ${blasting.delay_trend}`}/><div className="detail-stack"><MetricLine label="Rainfall 30d" value={`${number(weather.rainfall_30d_mm, 1)} mm`}/><MetricLine label="Temperature" value={`${number(weather.temperature_c, 1)} °C`}/><MetricLine label="Planned blasts / 7d" value={number(blasting.planned_blasts_7d)}/><MetricLine label="Blast delay / 7d" value={`${number(blasting.delay_hours_7d, 1)} h`}/></div></section><section className="panel wide"><PanelHeader icon={Target} title="Operating Window Signal" meta="decision support"/><p className="muted">Use environmental conditions and blast overlap as investigation signals. They do not replace site-specific safety procedures, geotechnical controls, blast clearance or supervisor approval.</p></section></div>; }

function RecommendationsPage({ initial }: { initial: RecommendationResponse }) { const [items, setItems] = useState(initial.recommendations); const [message, setMessage] = useState<string | null>(null); const simulate = async (id: string) => { try { const result = await apiPost<{ status: string }>("/api/v1/recommendations/simulate", { recommendation_id: id }); setMessage(result.status); setItems(current => current.map(item => item.id === id ? { ...item, status: "SIMULATED" } : item)); } catch (error) { setMessage(`Simulation failed: ${String(error)}`); } }; return <div className="page-grid"><section className="panel wide"><PanelHeader icon={Target} title="AI Action Center" meta={`${items.length} proposed actions · human approval`}/>{message && <div className="notice">{message}</div>}<div className="recommendation-list">{items.map(item => <article className="recommendation" key={item.id}><div className="rec-head"><span className={`priority ${item.priority.toLowerCase()}`}>{item.priority}</span><span>{item.status}</span></div><h3>{item.title}</h3><p>{item.rationale}</p><div className="evidence-grid"><MetricLine label="Confidence" value={percent(item.confidence)}/><MetricLine label="Equipment" value={item.affected_equipment.join(", ") || "—"}/></div><button className="action-button" onClick={() => void simulate(item.id)}>Simulate impact</button></article>)}</div></section></div>; }

function HealthPage({ models, dataQuality, boundary }: { models: ModelRegistryResponse; dataQuality: DataQualityResponse; boundary: string }) { const healthy = models.models.filter(model => model.status.toLowerCase().includes("active") || model.status.toLowerCase().includes("ready")).length; return <div className="page-grid"><section className="kpi-grid"><MetricCard icon={ShieldCheck} label="Data quality" value={percent(dataQuality.overall_score)}/><MetricCard icon={Database} label="Datasets checked" value={number(dataQuality.runs.length)}/><MetricCard icon={Activity} label="Models ready" value={`${healthy}/${models.models.length}`}/></section><section className="panel wide table-panel"><PanelHeader icon={Database} title="Data Health" meta="schema · freshness · completeness"/><div className="data-table-wrap"><table><thead><tr><th>Dataset</th><th>Rows</th><th>Missing</th><th>Duplicates</th><th>Schema</th><th>Score</th></tr></thead><tbody>{dataQuality.runs.map(run => <tr key={run.dataset_name}><td>{run.dataset_name}</td><td>{number(run.row_count)}</td><td>{percent(run.missing_rate)}</td><td>{percent(run.duplicate_rate)}</td><td>{run.schema_valid ? "VALID" : "CHECK"}</td><td>{percent(run.quality_score)}</td></tr>)}</tbody></table></div></section><section className="panel wide table-panel"><PanelHeader icon={Activity} title="Model Health" meta="registry snapshot"/><div className="data-table-wrap"><table><thead><tr><th>Model</th><th>Task</th><th>Algorithm</th><th>Version</th><th>Status</th></tr></thead><tbody>{models.models.map(model => <tr key={`${model.model_name}-${model.version}`}><td>{model.model_name}</td><td>{model.task}</td><td>{model.algorithm}</td><td className="mono">{model.version}</td><td>{model.status}</td></tr>)}</tbody></table></div></section><section className="panel wide"><PanelHeader icon={ShieldCheck} title="Validation Boundary" meta="SIH safety language"/><p className="muted">{boundary}</p><p className="muted">Model health indicators are engineering observability signals; they are not a substitute for domain validation, field QA/QC or operational authorization.</p></section></div>; }

function SettingsPage({ safety }: { safety: { mode: string; boundary: string } | null }) { return <div className="page-grid"><section className="panel wide"><PanelHeader icon={Settings} title="System Configuration" meta="read-only demo controls"/><MetricLine label="Safety mode" value={safety?.mode ?? "UNKNOWN"}/><MetricLine label="Data mode" value="DEMO / SYNTHETIC"/><MetricLine label="Decision boundary" value="Human approval required"/><p className="muted">{safety?.boundary ?? "Prototype outputs require validation before operational use."}</p></section><section className="panel"><PanelHeader icon={ShieldCheck} title="Scientific Guardrails" meta="enabled"/><ul className="guardrails"><li>Prototype resource potential, not official reserves.</li><li>Satellite imagery is contextual evidence.</li><li>Recommendations require human approval.</li><li>Demo/synthetic labels remain visible.</li></ul></section></div>; }
